config/routes.rb
Rails.application.routes.draw do
  	resources :categories do
  		resources :posts
  	end
  	resources :moods
  	resources :todos
	resources :users, only: [:index, :create, :destroy, :edit, :update]
	resources :roles
	get "/enter" => "missionboard#enter", as: "enter"
	get "/missionboard" => "missionboard#show", as: "missionboard"
	get "/exit" => "missionboard#exit", as: "exit"
	root "users#index"
end

app/models/mood.rb
class Mood < ApplicationRecord
	has_many :users
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  # GET /moods
  # GET /moods.json
  def index
    @moods = Mood.all
  end

  # GET /moods/1
  # GET /moods/1.json
  def show
  end

  # GET /moods/new
  def new
    @mood = Mood.new
  end

  # GET /moods/1/edit
  def edit
  end

  # POST /moods
  # POST /moods.json
  def create
    @mood = Mood.new(mood_params)

    respond_to do |format|
      if @mood.save
        format.html { redirect_to @mood, notice: 'Mood was successfully created.' }
        format.json { render :show, status: :created, location: @mood }
      else
        format.html { render :new }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moods/1
  # PATCH/PUT /moods/1.json
  def update
    respond_to do |format|
      if @mood.update(mood_params)
        format.html { redirect_to @mood, notice: 'Mood was successfully updated.' }
        format.json { render :show, status: :ok, location: @mood }
      else
        format.html { render :edit }
        format.json { render json: @mood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moods/1
  # DELETE /moods/1.json
  def destroy
    @mood.destroy
    respond_to do |format|
      format.html { redirect_to moods_url, notice: 'Mood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mood
      @mood = Mood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mood_params
      params.require(:mood).permit(:name)
    end
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/views/moods/_form.html.erb
<%= form_for(mood) do |f| %>
  <% if mood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mood.errors.count, "error") %> prohibited this mood from being saved:</h2>

      <ul>
      <% mood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moods/edit.html.erb
<h1>Editing Mood</h1>

<%= render 'form', mood: @mood %>

<%= link_to 'Show', @mood %> |
<%= link_to 'Back', moods_path %>

app/views/moods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Moods</h1>

<table>
  <thead>
    <tr>
      <th>Mood</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moods.each do |mood| %>
      <tr>
        <td><%= mood.name %></td>
        <td><%= link_to 'Show', mood %></td>
        <td><%= link_to 'Edit', edit_mood_path(mood) %></td>
        <td><%= link_to 'Destroy', mood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mood', new_mood_path %>

app/views/moods/new.html.erb
<h1>New Mood</h1>

<%= render 'form', mood: @mood %>

<%= link_to 'Back', moods_path %>

app/views/moods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mood:</strong>
  <%= @mood.name %>
</p>

<%= link_to 'Edit', edit_mood_path(@mood) %> |
<%= link_to 'Back', moods_path %>