config/routes.rb
Rails.application.routes.draw do
  	resources :categories do
  		resources :posts
  	end
  	resources :moods
  	resources :todos
	resources :users, only: [:index, :create, :destroy, :edit, :update]
	resources :roles
	get "/enter" => "missionboard#enter", as: "enter"
	get "/missionboard" => "missionboard#show", as: "missionboard"
	get "/exit" => "missionboard#exit", as: "exit"
	root "users#index"
end

app/controllers/missionboard_controller.rb
class MissionboardController < ApplicationController

  def enter
		session[:current_user_id] = params[:user_id]
		redirect_to missionboard_path
	end

  def show
  	@user = current_user
  	@users = User.all
  	@roles = Role.all
    @todos = Todo.all
    @moods = Mood.all
    @categories = Category.all
  end

  def exit
  	session[:current_user_id] = nil
  	redirect_to root_path
	end

  private
    # Use callbacks to share common setup or constraints between actions.
end

app/views/missionboard/show.html.haml
.container-fluid	
	.row.header
		.col-md-6.roles
			- @roles.each do |role|
				.col-md-2
					%h4= role.name
					= form_for(role) do |f|
						= select_tag 'role[user_id]', options_from_collection_for_select(@users, "id", "name", role.user.try(:id)), onchange: "this.form.submit()"
		.col-md-2.mood
			%h4 My Mood
			= form_for(current_user) do |f|
				= select_tag 'user[mood_id]', options_from_collection_for_select(@moods, "id", "name", current_user.mood.try(:id)), onchange: "this.form.submit()"
		.col-md-3.user
			%h4= @user.name
			- if @user.photo.present?
				%div= image_tag @user.photo, style: 'width: 50px; height: 50px'
			- else
				"No photo"
		.col-md-1.exit
			%h4= link_to "Exit", exit_path
	.row.main
		.col-md-4.sidebar1
			%h3.heading Mood Board
			%ul
				- @moods.each do |mood|
					.col-md-4
						%h4= mood.name
						- mood.users.each do |user|
							= user.name
		.col-md-8.body1
			%h3.heading To Do
			%table.table.table-striped
				.table-responsive
					%thead
						%tr
							%th Title
							%th Desctiption
							%th Status
							%th Due Date
							%th Asignees
							%th
							%th
					%tbody
						- @todos.each do |todo|
							%tr
								%td= todo.title
								%td= todo.description
								%td= todo.status
								%td= todo.due_date
								%td= todo.image
								%td= link_to "Edit", edit_todo_path(todo)
								%td= link_to "Delete", todo , method: :delete, data: { confirm: 'Are you sure?' }
			%div.new= link_to "New To Do", new_todo_path
	.row.main2
		- @categories.each do |category|
			.col-md-4.posts
				%h3.heading= category.name
				- category.posts.each do |post|
					.col-md-6
						%h4= post.title
						%p= post.body
						= link_to 'Show', category_post_path(category, post)
						= link_to 'Edit', edit_category_post_path(category, post)
						= link_to 'Destroy', category_post_path(category, post), method: :delete, data: { confirm: 'Are you sure?' }
				%div.new= link_to "New Post", new_category_post_path(category)
		%div.new= link_to "New Category", new_category_path